import Head from 'next/head'
import Link from 'next/link'
import { motion } from 'framer-motion'
import { FaArrowDown, FaChevronRight } from 'react-icons/fa'
import Navigation from '../components/Navigation';
import Projects from '../components/project';
import ContactForm from '../components/ContactForm';
import Footer from '../components/Footer';

const animateLoad = {
  hidden: { 
    scale: .8,
    opacity: 0 
  },
  show: {
    scale: 1,
    opacity: 1
  }
}

const animateScroll = {
  offscreen: {
    opacity: 0,
    y: 50
  },
  onscreen: {
    opacity: 1,
    y: 0,
  }
}

export default function Main() {


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <title>Ronel Florida | Future Full Stack Developer</title>
      </Head>

      {/* main content */}
      <div>

        {/* header */}
        <header className={`overflow-hidden relative w-full h-auto min-h-screen 
                            bg-[url('/images/Background-mobile.webp')] 
                            md:bg-[url('/images/Tablet-background.webp')] 
                            lg:bg-[url('/images/desktop-background.jpg')] bg-no-repeat 
                            bg-cover bg-opacity-[30%]`}>
              <Navigation />

              {/* HERO SECTION*/}
              <div className='absolute inset-0 bg-gray opacity-[90%]'></div>
              <main className='container relative w-full h-auto min-h-screen flex justify-center items-center text-center'>
                <div className='z-20'>
                  <motion.h1 
                    initial="hidden"
                    animate="show"
                    transition={{delay: .2}}
                    variants={animateLoad}
                    className='text-[2.3125rem] md:text-[3.75rem] lg:text-[5rem] transition-all ease-out duration-150 mb-4'
                  >
                    HI, I’M <span className='text-light-blue'>RONEL FLORIDA.</span>
                  </motion.h1>
                  <motion.p 
                    initial="hidden"
                    animate="show"
                    transition={{delay: .3}}
                    variants={animateLoad}
                    className=' text-[1.0625rem] md:text-[1.25rem] lg:text-[1.5625rem] lg:max-w-3xl lg:mx-auto mb-10'
                  >
                        Future <span className='font-bold'>Full Stack Developer</span>. I enjoy creating 
                        website and web applications. I'm currently learning <span className='font-bold'>React</span> and 
                        improving my problem-solving skills to become a good developer/programmer.
                  </motion.p>
                  <motion.div 
                    initial="hidden"
                    animate="show"
                    transition={{delay: .4}}
                    variants={animateLoad}
                    className='h-auto w-auto flex items-center justify-center'
                  >
                    <Link
                      href='/projects'
                      className='inline-block text-sm lg:text-base relative bg-dark py-4 px-5 tracking-[0.0625rem] leading-none z-10
                                overflow-hidden text-gray hover:text-gray after:content-[""] after:absolute
                                after:inset-0 after:bg-light-blue after:translate-x-[-101%] hover:after:translate-x-0 after:z-[-1]
                                after:transition-transform after:ease-in-out after:duration-300'
                    >
                      CHECK MY WORKS!
                    </Link>
                  </motion.div>
                </div>
                <div className='absolute bottom-5 left-2/4 translate-x-[-50%] hidden md:flex flex-col items-center'>
                  <div className="animate-bounce mb-1">
                    <FaArrowDown className='text-[1rem] text-light-blue'/>
                  </div>
                  <p className='text-[0.8125rem] tracking-[0.1875rem] text-light-blue'>SCROLL DOWN</p>
                </div>
              </main>

        </header>

        {/* about section */}
        <section id='about'  className='h-auto w-100 bg-light-dark text-gray py-[7.5625rem] overflow-hidden'>
          <div className='container'>

            {/* title */}
            <div className='text-center mb-[6.0625rem] md:mb-[8.125rem] lg:mb-36'>
              <motion.h3 
                initial='offscreen'
                whileInView='onscreen'
                variants={animateScroll}
                transition={{
                  type: "spring",
                  bounce: 0.5,
                  duration: 0.7,
                  delay: 0.2
                }}
                className='text-[1.5625rem] tracking-[0.0625rem] mb-6 md:text-4xl lg:text-[2.5rem]'
              >
                About me<span className='text-light-blue'>.</span>
              </motion.h3>
              <motion.p 
                initial='offscreen'
                whileInView='onscreen'
                variants={animateScroll}
                transition={{
                  type: "spring",
                  bounce: 0.5,
                  duration: 0.8,
                  delay: 0.3
                }}
                className='font-normal text-[0.9375rem] tracking-[0.0625rem] leading-6 md:max-w-xl md:mx-auto md:text-lg lg:text-xl'
              >
                Here you will find information about me, My currrent skills 
                and technology the I’ve been working with.
              </motion.p>
            </div>
            {/* end title */}

            {/* content */}
            <div className='grid grid-cols-1 grid-rows-auto gap-y-16 lg:grid-cols-2 lg:gap-x-8'>

              <div>
                <motion.h4
                  initial='offscreen'
                  whileInView='onscreen'
                  variants={animateScroll}
                  transition={{
                    type: "spring",
                    bounce: 0.5,
                    duration: 0.7,
                    delay: 0.4
                  }}
                  className='font-semibold text-lg tracking-[0.0625rem] mb-3 md:text-[1.625rem] md:mb-7 lg:text-xl'
                >
                  GET TO KNOW ME<span className='text-light-blue'>!</span>
                </motion.h4>
                <motion.p
                  initial='offscreen'
                  whileInView='onscreen'
                  variants={animateScroll}
                  transition={{
                    type: "spring",
                    bounce: 0.5,
                    duration: 0.7,
                    delay: 0.5
                  }}
                  className='font-normal text-[0.9375rem] tracking-[0.0625rem] leading-6 mb-4 md:text-xl md:leading-[1.875rem] md:mb-8 lg:text-lg lg:mb-9'
                >
                  Hello, I'm Ronel and I am aspiring <span className='font-bold'>Full Stack Web Developer</span>, I'm graduated
                  with the bachelor degree in information technology. I enjoy creating
                  things related to web. My interest in coding specially in web development
                  started when I was fourth year in college.
                </motion.p>
                <motion.p 
                  initial='offscreen'
                  whileInView='onscreen'
                  variants={animateScroll}
                  transition={{
                    type: "spring",
                    bounce: 0.5,
                    duration: 0.7,
                    delay: 0.6
                  }}
                  className='font-normal text-[0.9375rem] tracking-[0.0625rem] leading-6 mb-4 md:text-xl md:leading-[1.875rem] md:mb-8 lg:text-lg lg:mb-9'
                >
                  {/* I'm Introvert person I always feel comfortable being alone. I like Sci-fi movies
                  and anime. I also develop many personal project and I'm happy to share with you 
                  so please check in the <span className='font-bold'>Project</span> section. */}
                  I am a motivated and enthusiastic self-taught web developer with a passion for learning new 
                  technologies. I am constantly looking for ways to improve my skills and expand my knowledge. 
                  
                </motion.p>
                <motion.p
                  initial='offscreen'
                  whileInView='onscreen'
                  variants={animateScroll}
                  transition={{
                    type: "spring",
                    bounce: 0.5,
                    duration: 0.7,
                    delay: 0.7
                  }}
                  className='font-normal text-[0.9375rem] tracking-[0.0625rem] leading-6 md:text-xl md:leading-[1.875rem] md:mb-8 lg:text-lg lg:mb-9'
                >
                  I did'nt have any work experience so that my goal now is to get hired by one of the IT company here in
                  the philippines because I want to experience a real world projects to learn and improve more
                  in this field and also to enhance my problem solving skills.
                </motion.p>
              </div>

              {/* skills */}
              <div>
                <motion.h4
                  initial='offscreen'
                  whileInView='onscreen'
                  variants={animateScroll}
                  transition={{
                    type: "spring",
                    bounce: 0.5,
                    duration: 0.7,
                    delay: 0.4
                  }}
                  className='font-semibold text-lg tracking-[0.0625rem] mb-3 md:text-[1.625rem] md:mb-7 lg:text-xl'
                >
                  TECHNOLOGY THAT I’VE BEEN WORKING WITH<span className='text-light-blue'>!</span>
                </motion.h4>
                <motion.div
                  initial='offscreen'
                  whileInView='onscreen'
                  variants={animateScroll}
                  transition={{
                    type: "spring",
                    bounce: 0.5,
                    duration: 0.7,
                    delay: 0.5
                  }}
                  className='flex flex-wrap gap-6 text-light-dark font-semibold text-[1.0625rem] tracking-[0.0625rem]'
                >
                  <div
                    className='py-3 px-4 bg-gray'
                  >
                    HTML
                  </div>
                  <div 
                    className='py-3 px-4 bg-gray'
                  >
                    CSS
                  </div>
                  <div 
                    className='py-3 px-4 bg-gray'
                  >
                    Javascript
                  </div>
                  <div
                    className='py-3 px-4 bg-gray'
                  >
                    SASS
                  </div>
                  <div 
                    className='py-3 px-4 bg-gray'
                  >
                    NODE
                  </div>
                  <div 
                    className='py-3 px-4 bg-gray'
                  >
                    React
                  </div>
                  <div 
                    className='py-3 px-4 bg-gray'
                  >
                    TailwindCSS
                  </div>
                  <div 
                    className='py-3 px-4 bg-gray'
                  >
                    Responsive Design
                  </div>
                  <div  
                    className='py-3 px-4 bg-gray'
                  >
                    SQL Basic
                  </div>
                </motion.div>
              </div>

            </div>

          </div>
        </section>
        {/* end about section */}

        {/* project section */}
        <section id='projects' className='h-auto w-100 bg-gray text-light-dark py-[7.5625rem] overflow-hidden'>
          <div className='container'>

             {/* title */}
            <div className='text-center mb-[6.0625rem] md:mb-[8.125rem] lg:mb-36'>
              <motion.h3
                initial='offscreen'
                whileInView='onscreen'
                variants={animateScroll}
                transition={{
                  type: "spring",
                  bounce: 0.5,
                  duration: 0.7,
                  delay: 0.2
                }}
                className='text-[1.5625rem] tracking-[0.0625rem] mb-6 md:text-4xl lg:text-[2.5rem]'
              >
                My works<span className='text-light-blue'>.</span>
              </motion.h3>
              <motion.p
                initial='offscreen'
                whileInView='onscreen'
                variants={animateScroll}
                transition={{
                  type: "spring",
                  bounce: 0.5,
                  duration: 0.7,
                  delay: 0.3
                }}
                className='font-normal text-[0.9375rem] tracking-[0.0625rem] leading-6 md:max-w-xl md:mx-auto md:text-lg lg:text-xl'
              >
                Here you will find all of my personal projects 
                that I develop. 
              </motion.p>
            </div>
            {/* end title */}

            {/* project list */}
            <div>
              <Projects 
                imageSrc="/images/projects/url-shortening-landingPage.webp"
                title="Url Shortening Landing Page"
                techUse={["Html", "Sass", "Javascript", "shrtcode API"]}
                sourceCode="https://github.com/Ronel028/URL-shortening-api"
                livePreview="https://url-shortening-api-psi.vercel.app/"
                description={<p className='font-normal text-[1rem] text-light-dark tracking-[0.0625rem] leading-6 mb-7 md:text-lg lg:mb-[2.875rem]'>
                                URL Shortly Landing page is challenge 
                                from <Link href="https://www.frontendmentor.io/" className='font-bold hover:underline'>Frontend Mentor.</Link>
                                This landing page can make the long url links convert into short url by the
                                help of <Link href="https://shrtco.de/" className='font-bold hover:underline'>shrtcode API</Link>
                            </p>}
              flex_row="lg:flex-row"
              />
              <Projects 
                imageSrc="/images/projects/advice-generator-app.webp"
                title="Advice Generator App"
                techUse={["Vite", "Sass", "Javascript", "Advice Slip API"]}
                sourceCode="https://github.com/Ronel028/fem-advice-generator"
                livePreview="https://web-advice-generator.herokuapp.com/"
                description={<p className='font-normal text-[1rem] text-light-dark tracking-[0.0625rem] leading-6 mb-7 md:text-lg lg:mb-[2.875rem]'>
                                Advice generator app is challenge 
                                from <Link href="https://www.frontendmentor.io/" className='font-bold hover:underline'>Frontend Mentor. </Link>
                                That you can generate random advice from <Link href="https://api.adviceslip.com/" className='font-bold hover:underline'>Advice Slip API.</Link>
                            </p>}
                flex_row="lg:flex-row-reverse"
              />
              <Projects 
                imageSrc="/images/projects/bms.webp"
                title="Barangay Management System"
                techUse={["React", "Node", "Express", "Bootstrap", "Sass", "MySql"]}
                sourceCode="https://github.com/Ronel028/barangay-management-system-final"
                livePreview="https://github.com/Ronel028/barangay-management-system-final"
                description={<p className='font-normal text-[1rem] text-light-dark tracking-[0.0625rem] leading-6 mb-7 md:text-lg lg:mb-[2.875rem]'>
                                Barangay Management System is my personal project. I develop this in order to
                                practice my self in front-end and back-end development and also in database which is MySql.
                                This project has a CRUD functionality that you can create, read, update, and delete data of
                                Barangay Official, resident, blotter, and certificate.

                            </p>}
                flex_row="lg:flex-row"
              />
            </div>
            {/* end project list */}

            {/* show more button */}
            <motion.div
              initial={{ opacity: 0, scale: .8 }}
              whileInView={{ opacity: 1, scale: 1 }}
              transition={{
                  type: 'spring',
                  bounce: 0.5,
                  duration: 0.6,
                  delay: 0.3
              }}
              className='w-full flex items-center justify-center'>
              <Link 
                href="/projects"
                className='flex items-center gap-3 text-sm relative bg-dark py-4 px-5 justify-self-end tracking-[0.0625rem] leading-none z-10
                overflow-hidden text-gray hover:text-gray after:content-[""] after:absolute
                after:inset-0 after:bg-light-blue after:translate-x-[-101%] hover:after:translate-x-0 after:z-[-1]
                after:transition-transform after:ease-in-out after:duration-300'>

                <p className=' tracking-[0.0625rem]'>CHECK MORE!</p>
                <FaChevronRight className='text-sm'/>

              </Link>
            </motion.div>
          </div>
        </section>

        {/* contact section */}
        <section id='contact' className='h-auto w-100 bg-light-dark text-gray py-[7.5625rem] overflow-hidden'>
          <div className='container'>  

            {/* title */}
            <div className='text-center mb-[6.0625rem] md:mb-[8.125rem] lg:mb-36'>
              <motion.h3
                initial='offscreen'
                whileInView='onscreen'
                variants={animateScroll}
                transition={{
                  type: "spring",
                  bounce: 0.5,
                  duration: 0.7,
                  delay: 0.2
                }}
                className='text-[1.5625rem] tracking-[0.0625rem] mb-6 md:text-4xl lg:text-[2.5rem]'
              >
                Contact<span className='text-light-blue'>.</span>
              </motion.h3>
              <motion.p 
                initial='offscreen'
                whileInView='onscreen'
                variants={animateScroll}
                transition={{
                  type: "spring",
                  bounce: 0.5,
                  duration: 0.7,
                  delay: 0.3
                }}
                className='font-normal text-[0.9375rem] tracking-[0.0625rem] leading-6 md:max-w-[40.8125rem] md:mx-auto md:text-lg lg:text-xl'
              >
                I’m open to job opportunity related to web development where 
                I can contribute, learn and grow. If you have good opportunity 
                that matches my skills then don’t hesitate to contact me.  
              </motion.p>
            </div>
            {/* end title */}

            {/* contact form */}
            <div>
              <ContactForm />
            </div>
          </div>
        </section>

        {/* footer */}
        <Footer />

      </div>
    </>
  )
}
